26/10/2020 07:11:40 PM Python Script is: morePVs.py
26/10/2020 07:11:40 PM study_name = pt_mike_test
26/10/2020 07:11:49 PM Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
26/10/2020 07:11:49 PM NumExpr defaulting to 8 threads.
26/10/2020 07:11:49 PM saved to C:\Users\z5044992\Documents\python\morePVs\DATA_EN_MR1\studies\latest24-9\outputs\pt_mike_test\saved_tariffs\static_import_tariffs.csv
26/10/2020 07:11:50 PM saved to C:\Users\z5044992\Documents\python\morePVs\DATA_EN_MR1\studies\latest24-9\outputs\pt_mike_test\saved_tariffs\static_solar_import_tariffs.csv
26/10/2020 07:11:50 PM saved to C:\Users\z5044992\Documents\python\morePVs\DATA_EN_MR1\studies\latest24-9\outputs\pt_mike_test\saved_tariffs\static_export_tariffs.csv
26/10/2020 07:11:50 PM Running Scenario number 0 
26/10/2020 07:11:50 PM 


 Exception !!!!!!
Traceback (most recent call last):
  File "C:/Users/z5044992/Documents/python/morePVs/morePVs.py", line 2667, in main
    runScenario(s)
  File "C:/Users/z5044992/Documents/python/morePVs/morePVs.py", line 2588, in runScenario
    eno = Network(scenario=scenario)
  File "C:/Users/z5044992/Documents/python/morePVs/morePVs.py", line 1160, in __init__
    self.network.tot_fixed = 0
AttributeError: 'Network' object has no attribute 'network'
