30/08/2019 11:34:18 AM Python Script is: morePVs.py
30/08/2019 11:34:18 AM study_name = test_capex2
30/08/2019 11:34:18 AM Running Scenario number 1 
30/08/2019 11:35:06 AM **************CHECKSUM ERROR************************
30/08/2019 11:35:06 AM Study: test_capex2  Scenario: 1 
30/08/2019 11:35:06 AM Tot Building Cost 63189.219358 Checksum -63189.219358
30/08/2019 11:35:06 AM Completed Scenario 1
30/08/2019 11:35:06 AM Running Scenario number 2 
30/08/2019 11:35:37 AM 


 Exception !!!!!!
Traceback (most recent call last):
  File "/Users/mikeroberts/Documents/python/morePVs/morePVs.py", line 2656, in main
    runScenario(s)
  File "/Users/mikeroberts/Documents/python/morePVs/morePVs.py", line 2619, in runScenario
    eno.allocateAllCapex(scenario)  # per load profile to allow for scenarios where capex allocation depends on load
  File "/Users/mikeroberts/Documents/python/morePVs/morePVs.py", line 1601, in allocateAllCapex
    self.resident[c].pv_capex_repayment = scenario.pv_capex_repayment[c]
KeyError: 'central'
