30/08/2019 10:53:02 AM Python Script is: morePVs.py
30/08/2019 10:53:02 AM study_name = test_capex1
30/08/2019 10:53:03 AM Running Scenario number 1 
30/08/2019 10:53:05 AM Completed Scenario 1
30/08/2019 10:53:05 AM Running Scenario number 2 
30/08/2019 10:53:09 AM Completed Scenario 2
30/08/2019 10:53:09 AM Running Scenario number 0 
30/08/2019 10:53:09 AM 


 Exception !!!!!!
Traceback (most recent call last):
  File "/Users/mikeroberts/Documents/python/morePVs/morePVs.py", line 2653, in main
    runScenario(s)
  File "/Users/mikeroberts/Documents/python/morePVs/morePVs.py", line 2616, in runScenario
    eno.allocateAllCapex(scenario)  # per load profile to allow for scenarios where capex allocation depends on load
  File "/Users/mikeroberts/Documents/python/morePVs/morePVs.py", line 1570, in allocateAllCapex
    pv_owners = self.scenario.pv_capex.keys()
AttributeError: 'Scenario' object has no attribute 'pv_capex'
